require("telescope").load_extension("live_grep_args")
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.git_files, {})
vim.keymap.set('n', '<leader>fr', function()
  require("telescope").extensions.live_grep_args.live_grep_args()
end)
vim.keymap.set('n', '<leader>regex', ':!open "https://docs.rs/regex/1.9.5/regex/\\#syntax"<CR>')
